#!/bin/sh /etc/rc.common

START=99
STOP=15

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/gowebdav -dir $(uci get webdav.@webdav[0].dir) -port $(uci get webdav.@webdav[0].port)
    [ "$(uci get webdav.@webdav[0].https_mode)" = "1" ] && procd_append_param command -https-mode -https-cert-file $(uci get webdav.@webdav[0].https_cert_file) -https-key-file $(uci get webdav.@webdav[0].https_key_file)
    [ "$(uci get webdav.@webdav[0].user)" != "" ] && procd_append_param command -user $(uci get webdav.@webdav[0].user) -password $(uci get webdav.@webdav[0].password)
    [ "$(uci get webdav.@webdav[0].read_only)" = "1" ] && procd_append_param command -read-only
    [ "$(uci get webdav.@webdav[0].show_hidden)" = "1" ] && procd_append_param command -show-hidden
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall gowebdav
}