include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-gowebdav
PKG_VERSION:=1.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for GoWebDav
LUCI_DEPENDS:=+gowebdav
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk